### ISSUE TITLE
Console output vs. browser document output

### ISSUE THREAD

**Issue by chadunit** [fable-compiler/repl2#14]
Some of the samples use printfn output. For new users who maybe aren't already experienced JS/web devs, it may not be obvious that they need to open the console to see anything. So their initial "hello world" experience is a blank white page and nothing happening.

Maybe there should be a note or comment somewhere to "please open your browser console to see program output".

Or, maybe the samples should prefer browser document output instead of printfn for primary program output, e.g.:
```
open Fable.Import.Browser
let addToBody text =
    let textNode = document.createTextNode text
    let divNode = document.createElement_div()
    divNode.appendChild textNode |> ignore
    document.body.appendChild divNode |> ignore

addToBody "Hello World"
```

**Comment by MangelMaxime** [comment]
We are planning to add a console output tab in the layout.

Using the document to ouput code isn't really beginner friendly when you see the `ignore` needed etc.

An quick fix could be to add a comment in the sample that use `printfn` in their code to show the result. 

If you want to send a PR, the samples are [here](https://github.com/fable-compiler/repl2/tree/master/public/samples)

**Comment by chadunit** [comment]
Added code comment and additional hello world sample using simpler HTML element modification in #15.
