### ISSUE TITLE
Hidden tooltips close to the top

### ISSUE THREAD

**Issue by ncave** [fable-compiler/repl2#20]
Tooltips close to the top are partially obscured, it's like Monaco thinks there is enough space to show them under the header bar. Also tooltips are squashed if too close to the right, instead of showing to the left.

Idk if this is fixable, definitely not something to spend much time on, just posting it in case somebody has a simple solution from the top of their heads.

**Comment by MangelMaxime** [comment]
I saw it for the top and didn't think it was a problem because if we have a comment and/or a module in general it's ok.

For the right part I didn't see it coming :) Not sure, if we can fix it... Perhaps, it's due to how the page is constructed will try to take a look at the CSS.

**Comment by ncave** [comment]
@MangelMaxime I noticed the same thing in VS Code, but it's rare. Most of the time the tooltip shows on top of the header, I wonder if we can do the same somehow (put the header behind the tooltip):

![image](https://user-images.githubusercontent.com/777696/44323030-00cc9780-a405-11e8-9ecd-d41a00605253.png)

**Comment by MangelMaxime** [comment]
Hum there is not much we can do here...

And it's probably a bug in Monaco because some tooltip works as expected:

![repl_tooltipebug_top](https://user-images.githubusercontent.com/4760796/45244665-185aba00-b2f9-11e8-93e7-55d73fef24a5.gif)

**Comment by Nhowka** [comment]
Continuing #73, `z-index: 12000; position: fixed` on the style fixes the tooltip too:
![image](https://user-images.githubusercontent.com/10579995/48279962-46639400-e439-11e8-9bc8-a36434a446f0.png)
