### ISSUE TITLE
Inlined overloaded methods are not resolved properly without optimization

### ISSUE THREAD

**Issue by dgchurchill** [fable-compiler/repl2#21]
Using http://fable.io/repl2 (Version: 2.0.0-beta-001) the following code:

```
type InlineTest() =
    static member inline OverloadedInline(_ : int) : int =
        2

    static member inline OverloadedInline(_ : string) : string =
        "hello"

printfn "%A" (InlineTest.OverloadedInline 1)
printfn "%A" (InlineTest.OverloadedInline "1")
```

Prints `2` twice instead of printing `2` and `"hello"`.

However, if the `Optimize (experimental)` option is turned on then it works as expected.

**Comment by dgchurchill** [comment]
Sorry just realize the raise a bug link links to the repl2 repo. I'll re-raise this in the compiler repo.

**Comment by alfonsogarciacaro** [comment]
Hmm, this seems to affect only the REPL. Your code works with the dotnet-fable CLI tool. Maybe the overload resolution becomes somehow flaky after the JS compilation. Let's keep the issue here until we can investigate :+1:

**Comment by MangelMaxime** [comment]
It's now fixed in latest REPL.
