### ISSUE TITLE
Fix display of the Reset link on the loading page

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/repl2#24]
The Reset link in the loading page is hard to see.

It's grey over white and when over it's white.

We should customize the loading to use a dark theme like the rest of the REPL.

**Comment by alfonsogarciacaro** [comment]
No worries @xdaDaveShaw, this only disturbs to people that have some sense of aesthetics like @MangelMaxime. For people like me that have none it looks fine 😆

**Comment by MangelMaxime** [comment]
Ahah :)

@xdaDaveShaw No worries. I want to change the loader since a long time but now I have an extra motivation :)
