### ISSUE TITLE
REPL is breaking with latest Fable master

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/repl2#26]
Not sure why but with latest Fable master the REPL hangs when compiling samples (I don't think is [this commit](https://github.com/fable-compiler/Fable/commit/fce0adeb4e9833de30d0a68e50ca9e91d3c24861) because I reverted to the commit before and the problem still happened). I reverted to [2.0.0-beta-004 release commit](https://github.com/fable-compiler/Fable/commit/fce0adeb4e9833de30d0a68e50ca9e91d3c24861) and everything seems to be working now. 

There are not so many commits affecting the code in between, it may have been the upgrade to FCS 25 or Babel 7. I'll investigate more after the presentation.

cc @ncave @MangelMaxime

**Comment by alfonsogarciacaro** [comment]
Also replying to @MangelMaxime's question [here](https://github.com/fable-compiler/Fable/commit/73961ae4a2beb2532c7d9edc34eb9a871cc007f7#commitcomment-30552016).

This was definitely caused by the upgrade to Babel 7, I've reverted Fable master now to Babel 6 and it seems to work. Unfortunately I cannot know what was the exact problem without more extensive debugging, the REPL just hangs [in this line](https://github.com/fable-compiler/repl2/blob/59c361b97a46323395ddbd5a2c3f82b9b7f48ecc/src/Worker/Worker.fs#L43).

@MangelMaxime If you want to test it, you can change the Fable branch [here](https://github.com/fable-compiler/repl2/blob/59c361b97a46323395ddbd5a2c3f82b9b7f48ecc/build.fsx#L1) to `repl-babel7` which holds the state of master before the "Revert to Babel 6 to fix REPL" commit. Then run the `WatchApp` build target and you should also get the hanging compilation (for any sample but the Hello World ones).

In any case, you can start working in #27 if you want, as this issue is now solved :)

**Comment by MangelMaxime** [comment]
Thank you for the explanation. 

Hum, I must admit my F# test code is simple for now:

```fs
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
pintfn "Hello World" // writes to the dev tools console
```

So it's probably doesn't trigger the problem. :man_shrugging:

**Comment by alfonsogarciacaro** [comment]
After a lot of testing I finally found the issue, it wasn't Babel 7... but Rollup! For some reason it was duplicating some variables. I've replaced it with Webpack to build the REPL and everything seems to be working now :smile:

**Comment by alfonsogarciacaro** [comment]
Nope, I was wrong (again). Apparently it had to do with transpilation to ES5 + minification or another combination of related factors. Just replacing Rollup with Webpack didn't help, I'm now suppressing the Babel env preset (so ES2015 features are kept) and minifying with terser (as @ncave already advised some weeks ago).

It looks like using ES2015 somewhat increases the performance of the REPL, but it may also be an illusion just because I'm so happy that it's woking :)

I would love to know what was exactly the problem, but for now let's just hope it doesn't como across any other project 🙏
