### ISSUE TITLE
More feedback about compilation (when completed and result)

### ISSUE THREAD

**Issue by codec-abc** [fable-compiler/repl2#27]
Hi,

I was playing with the Fable 2 REPL and was very impressed by how easy and intuitive it is for new users. Yet, I have a small nitpick: 

It would be nice to add a notification when the compilation complete. For a example a small hovering popup (non modal) that tell that the compilation is either complete with either success or failure would be nice (maybe with a green/red color scheme to easily tell the case without having to read the text). Also, if compilation fail, being able to click on the popup and get details about the compilation errors would be a nice addition. I currently have an error in the dev tool when compilation fail but it isn't ideal to get feedback. Also, the red wavy lines indicating errors seems to disappear after a compilation even if it failed which is not great.

**Comment by MangelMaxime** [comment]
Really happy that you find the REPL useful :)

**Note for the maintainers**

We can easily add notifications using [Thoth.Elmish.Toast](https://mangelmaxime.github.io/Thoth/elmish/toast_docs.html)

> Also, the red wavy lines indicating errors seems to disappear after a compilation even if it failed which is not great.

We should check if this happens all the time and if we can detect it. If yes, when detecting this situation we should not update the errors.

**Comment by MangelMaxime** [comment]
For info, I will give it a try.

**Comment by alfonsogarciacaro** [comment]
Thanks for the report @codec-abc. Would it be possible to post the sample code where the red lines disappear after a failed compilation?

@MangelMaxime, please let me investigate #26 first. If you use latest bundle from Appveyor the REPL may break.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Any code with an error can repro the red lines problem.

![2018-09-18 17 32 15](https://user-images.githubusercontent.com/4760796/45698690-dcc9b680-bb68-11e8-816e-56a3770c39c9.gif)

I didn't send an issue yet to Fable repo but I made a quick fix locally: https://github.com/fable-compiler/repl2/commit/d4fc327e2022b1e98122005e3880b4af5a34f4d0#diff-dcacc8ee23340bddc18fc021372d3df8R46

About #26, sure for now I am just preparing new features we can publish them later or use a previous version on the next publish.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Ah, you're right, thank you! I thought I had fixed that [in this commit](https://github.com/fable-compiler/Fable/commit/7655a99ea07c01e307d702031f23fa18836f1daf) but I was forgetting the parse errors 🤦‍♂️ I will add it to Fable so we don't need the manual fix in the REPL.
