### ISSUE TITLE
Make sudoku sample show something on the screen

### ISSUE THREAD

**Issue by forki** [fable-compiler/repl2#30]
in repl 1 it showed the printf output. I think someone should hook it up in the live html view

**Comment by alfonsogarciacaro** [comment]
Someone? Maybe the original autor? ;)

If we added UI, we would have to make it a proper Sudoku game and that's some work. Actually the Sudoku (and the Parser) sample is only there to profile the REPL. As we already have other samples for that, we could remove them if they're not a nice showcase.

**Comment by forki** [comment]
It's now showing console. So that's no regression to repl1 anymore.

**Comment by forki** [comment]
ok @alfonsogarciacaro you got me: https://github.com/fable-compiler/repl2/pull/39
