### ISSUE TITLE
Make REPL start with something cooler than hello world

### ISSUE THREAD

**Issue by forki** [fable-compiler/repl2#32]

**Comment by alfonsogarciacaro** [comment]
Hmm, the Hello World is like a "zero state" you can reset into when the REPL hangs. It's probably better to keep it for now, but if we'd change it, what would you use?

**Comment by forki** [comment]
We discussed a bit on fable gitter. Maxime ported his fulma intro. We think
that makes a nice very first sample.


Alfonso Garcia-Caro <notifications@github.com> schrieb am Mi., 26. Sep.
2018, 06:49:

**Comment by MangelMaxime** [comment]
The idea behind this request is if people discover Fable we want to provide a good first impression. We think showing `printfn "Hello world"` do not provide this kind of impression :)

By using the fulma intro, we show in one screen a clean and working example of Fable + Elmish. Which are already one of the main selling point of Fable.

And new people can start toying with it easily.
