### ISSUE TITLE
Hello world does not compile with activated "optimize"

### ISSUE THREAD

**Issue by forki** [fable-compiler/repl2#36]
![image](https://user-images.githubusercontent.com/57396/46066083-135c8e00-c174-11e8-8c7f-b5c069b064ab.png)

/cc @ncave

**Comment by MangelMaxime** [comment]
https://github.com/fable-compiler/Fable/issues/1573

**Comment by ncave** [comment]
@forki I'm guessing a new optimization introduced in FCS 25.0.1? Anyway, this can be fixed but there are other issues with optimized AST like the string operator over lists or tuples.

**Comment by alfonsogarciacaro** [comment]
Fixed now. Though, as @ncave says, there may still be some issues in other cases. That's why it's still experimental :)
