### ISSUE TITLE
Color Fountain not working in FireFox

### ISSUE THREAD

**Issue by selketjah** [fable-compiler/repl2#52]
The fountain doesn't start after compiling successfully.
Tested in Chrome and it works fine there.
Am I doing something wrong?

**Screenshot**

<img width="1678" alt="screen shot 2018-09-29 at 07 30 38" src="https://user-images.githubusercontent.com/2250570/46246972-cff36100-c3b9-11e8-9663-49da05478474.png">

**FireFox**

<img width="630" alt="screen shot 2018-09-29 at 07 34 45" src="https://user-images.githubusercontent.com/2250570/46247011-337d8e80-c3ba-11e8-9ca4-77d1019d67ff.png">

**Comment by MangelMaxime** [comment]
Can you please try with the latest version of Firefox `62.0.2`?

Because for me it's working with this one on OSX

**Comment by alfonsogarciacaro** [comment]
Color Fountain works fine for me with latest Firefox and macOS :/ Maybe [resetting](http://fable.io/repl2/#reset) helps?

**Comment by selketjah** [comment]
seeing how I'm the only one with this problem, I'm going to close this issue.

**Comment by MangelMaxime** [comment]
I am able to reproduce. Please, go into the options and disable the optimization.

![2018-10-03 20 19 54](https://user-images.githubusercontent.com/4760796/46430607-c49d8e00-c749-11e8-9895-e23945dd46ab.gif)
