### ISSUE TITLE
Add elmish validation sample 

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/repl2#65]
Just so that I don't forget, the code is in [elmish-login-flow-validation](https://github.com/Zaid-Ajaj/elmish-login-flow-validation)

**Comment by alfonsogarciacaro** [comment]
Ah, that'd be a very nice sample. For now, the only thing you need to do is to put everything in one single file. You can check [this commit](https://github.com/fable-compiler/repl2/commit/c6eac122631cde3b7dca3ec1f5c06e1e749df31c) as reference to add a sample.

**Comment by Zaid-Ajaj** [comment]
Looks simple enough, I will add it soonish ;)
