### ISSUE TITLE
Compile button is sometimes empty

### ISSUE THREAD

**Issue by ncave** [fable-compiler/repl2#9]
The focused version of the compile button is empty.

**Comment by alfonsogarciacaro** [comment]
I think it's because of the colors in the new theme.

**Comment by MangelMaxime** [comment]
Fixed in master branch

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I let you publish the new REPL version.

For the next time, what is the needed steps ? Just execute the `PublishGithubPages` target ?

**Comment by alfonsogarciacaro** [comment]
Yes, that should do everything. The only thing that's not included is the generation of new metadata if something changes (for example, new Fable.Core or Fable.Repl.Lib).
